config/routes.rb
PmTool::Application.routes.draw do

  root 'welcome#index'

  resources :projects, :only => [:create, :destroy], :shallow => true do
    resources :products, :only => [:index]
    resources :works, :only => [:index]
    resources :resources, :only => [:index]
    resources :resource_allocations, :only => [:index]
    resources :efforts, :only => [:index]
  end

  controller :products do
    post 'product', :to => :create
    patch 'product', :to => :move
    put 'product', :to => :update
    delete 'product', :to => :destroy
  end

  controller :works do
    post 'work', :to => :create
    patch 'work', :to => :move
    put 'work', :to => :update
    delete 'work', :to => :destroy
    get 'work/output', :to => :output
  end

  controller :resources do
    post 'resource', :to => :create
    patch 'resource', :to => :move
    put 'resource', :to => :update
    delete 'resource', :to => :destroy
    get 'resource', :to => :get
  end

  controller :resource_allocations do
    get 'resource_allocations', :to => :get
    get 'resource_allocations_select', :to => :select
    post 'resource_allocations', :to => :update
  end

  controller :efforts do
    delete 'efforts/:id/delete', :to => :destroy, :as => 'effort'
    post 'efforts', :to => :create
    get 'projects/:project_id/efforts/results', :to => :results, :as => 'efforts_results'
  end

  controller :milestones do
    get 'projects/:project_id/roadmap', :to => :index, :as => 'project_roadmap'
    post 'milestone', :to => :create
    delete 'milestone/:id/delete', :to => :destroy, :as => 'milestone_delete'
  end

end

app/models/work.rb
class Work < ActiveRecord::Base
  default_scope { order('position') }

  belongs_to :project
  has_ancestry :cache_depth => true
  belongs_to :output, :class_name => 'Product'
  has_many :resource_allocations
  has_many :resources, :through => :resource_allocations
  accepts_nested_attributes_for :resource_allocations
  has_many :efforts, :dependent => :destroy
  acts_as_list :scope => 'ancestry = \'#{ancestry}\''
  before_destroy :destroy_childs

  def to_json(otions)
    super(:only => [:id, :name, :parent_id, :position, :project_id, :output_id], :methods => [:depth])
  end

  def add_resource(resource, amount)
    ResourceAllocation.create(:work => self, :resource => resource, :amount => amount)
  end

  def expectation(type)
    # 1 - pessimistic
    # 2 - realistic
    # 3 - optimistic

    return self.efforts.expectation.where(:method => type).first
  end

  def average_estimate(group)
    if (group == 0) #delphi
      #estimations = self.efforts.delphi.map(&:estimation)
      avg = self.efforts.delphi.average(:estimation)#(estimations.sum.to_f / estimations.size) if !estimations.blank?
    else #expectation
      if (self.efforts.expectation.count >= 3)
        avg = (expectation(1).estimation + 4*expectation(2).estimation + expectation(3).estimation) / 6
      end
    end

    avg = avg.round(1) if !avg.nil?

    return avg
  end

private
  def destroy_childs
    self.children.delete_all
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:update, :move, :output, :destroy]

  def index
    @project = Project.find(params[:project_id])
    @works = @project.works
  end

  def create
    @work = Work.create(:name => params[:work][:name], :parent_id => params[:work][:parent], :project_id => params[:project])
    render :json => @work
  end

  def move
    @work.remove_from_list
    @work.parent_id = params[:work][:parent].to_f
    @work.save
    @work.insert_at(params[:work][:position].to_f)
    @work.save

    render :json => @work
  end

  def update
    @work.name = params[:work][:name]
    @work.output_id = params[:work][:output]
    @work.save

    render :json => @work
  end

  def output
    render :json => @work.output_id
  end

  def destroy
    @work.destroy

    render :json => @work
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:work][:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :position, :project_id, :parent_id, :output_id)
    end
end

app/views/works/index.html.erb
<%= render :partial => 'projects/navigation' %>
<h1>Work Breakdown Structure</h1>
<nav class="navbar navbar-default" role="navigation">
  <div class="collapse navbar-collapse">
    <div class="navbar-left">
      <button type="button" class="btn btn-sm navbar-btn" id="work-new"><span class="glyphicon glyphicon-plus"></span> New</button>
      <button type="button" class="btn btn-sm navbar-btn" id="work-rename"><span class="glyphicon glyphicon-pencil"></span> Rename</button>
      <button type="button" class="btn btn-sm navbar-btn" id="work-remove"><span class="glyphicon glyphicon-remove"></span> Remove</button>
    </div>
    <div class="btn btn-xs col-xs-3">
      <div class="input-group">
        <span class="input-group-addon"><span class="glyphicon glyphicon-share"></span></span>
        <%= select 'work', 'output_id', @project.products.at_depth(3).collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}, :class => 'form-control', :disabled => 'disabled', :'data-toggle' => 'tooltip', :'data-placement' => 'top', :'data-original-title' => 'Output of selected node' %>
      </div>
    </div>
    <div class="navbar-right">
      <%= form_for :work, :url => work_path, :html => { :class => 'navbar-form navbar-left pull-right', :style => 'display: none', :role => 'form', :id => 'new-work-form' } do |f| %>
        <div class="form-group">
          <%= f.text_field :name, :class => 'form-control', :placeholder => 'Enter node name' %>
        </div>
        <%= f.submit 'Insert', :class => 'btn btn-primary btn-sm' %>
      <% end %>
    </div>
  </div>
</nav>

<div id="jstree"></div>
<script>
  $('#jstree').jstree({
      "core" : {
        "check_callback" : true,
        "data" : {
          "url" : "<%= project_works_path(@project, :format => :json) %>",
          "data" : function(node) {
            return { 'id' : node.id, 'text' : 'test' };
          }
        },
      },
      "types" : {
        '#'  : { "icon" : "glyphicon glyphicon-folder-open", "valid_children" : [] },
        'd0' : { "icon" : "glyphicon glyphicon-folder-open", "valid_children" : ['d1'] },
        'd1' : { "icon" : "glyphicon glyphicon-folder-open", "valid_children" : ['d2'] },
        'd2' : { "icon" : "glyphicon glyphicon-folder-open", "valid_children" : ['d3'] },
        'd3' : { "icon" : "glyphicon glyphicon-tasks", "max_children" : 0, "valid_children" : [] }
      },
      "plugins" : [ "dnd", "types", "wholerow" ]
  }).bind('ready.jstree', function() {
    $(this).jstree('open_all').jstree('open_all').jstree('open_all');
  }).bind('set_text.jstree', function(event, data) {
    if (!!data.text) {
      var work = {
        'id' : data.obj.id,
        'name' : data.obj.text
      };
      AjaxWork('PUT', work, null);
    }
  }).bind('delete_node.jstree', function(event, data) {
    var work = {
      'id' : data.node.id
    }
    AjaxWork('DELETE', work, null);
  }).bind('move_node.jstree', function(event, data) {
    var work = {
      'id' : data.node.id,
      'parent' : data.parent,
      'position' : data.position + 1
    }
    AjaxWork('PATCH', work, null);
  }).bind('select_node.jstree', function(event, data) {
    if (data.node.type == 'd3') {
      var work = {
        'id' : data.node.id
      }

      $.ajax({
        type : 'GET',
        url : '<%= work_output_path %>',
        dataType: 'json',
        data : { 'project' : <%= @project.id %>, 'work' : work },
        success: function(data) {
          $('#work_output_id').val(data).removeAttr('disabled');
        },
        error: function(xhRequest, ErrorText, thrownError) {
          console.log(xhRequest.responseText);
        }
      });
    } else {
      $('#work_output_id').val('').attr('disabled', 'disabled');
    }
  });

  $('#work_output_id').tooltip();

  $('#work_output_id').change(function() {
    // TODO: Ajax update
    var ref = $('#jstree').jstree(true),
        sel = ref.get_selected();

    if(!sel.length) { return false; }
    sel = ref.get_node(sel[0]);

    var work = {
      'id' : sel.id,
      'name' : sel.text,
      'parent' : sel.parent,
      'output' : this.value
    }

    $.ajax({
      type : 'PUT',
      url : '<%= work_path %>',
      dataType: 'json',
      data : { 'project' : <%= @project.id %>, 'work' : work },
      error: function(xhRequest, ErrorText, thrownError) {
        console.log(xhRequest.responseText);
      }
    });
  })

  function AjaxWork(action, work, callback) {
    $.ajax({
      type : action,
      url : '<%= work_path %>',
      dataType: 'json',
      data : { 'project' : <%= @project.id %>, 'work' : work },
      success: callback,
      error: function(xhRequest, ErrorText, thrownError) {
        console.log(xhRequest.responseText);
      }
    });
  }

  $('#work-new').click(function() {
    $('#work_name').val('');
    $('#new-work-form').toggle('slide', function () { $('#work_name').focus() });
  });

  $('#work-rename').click(function() {
    var ref = $('#jstree').jstree(true),
        sel = ref.get_selected();

    if(!sel.length) { return false; }
    sel = sel[0];
    ref.edit(sel);
  });

  $('#work-remove').click(function() {
    var ref = $('#jstree').jstree(true),
        sel = ref.get_selected();

    if (!sel.length) { return false; }
    ref.delete_node(sel);
  });

  $('#new-work-form').validate({
    rules: {
      'work[name]': {
        required : true,
        validParentNodeSelected : true
      }
    },
    messages: {
      'work[name]': {
        validParentNodeSelected : 'Please select a valid parent node.'
      }
    },
    submitHandler: function(form) {
    var val = $('#work_name').val();
    var ref = $('#jstree').jstree(true),
        sel = ref.get_selected();

    sel = ref.get_node(sel[0]);

    if (sel.type != 'd3' || sel.type == '#') {
      var work = { 'name' : val, 'parent' : sel.id }

      AjaxWork('POST', work, function(data) {
        ref.create_node(sel,
          {
            'id' : data.id,
            'text' : data.name,
            'type' : 'd' + data.depth
          }
        );
        ref.open_node(sel);
      })

      $('#new-work-form').hide('slide');
    }
    }
  })

</script>