config/routes.rb
PmTool::Application.routes.draw do

  root 'welcome#index'

  resources :projects, :only => [:create, :destroy], :shallow => true do
    resources :products, :only => [:index]
    resources :works, :only => [:index]
    resources :resources, :only => [:index]
    resources :resource_allocations, :only => [:index]
    resources :efforts, :only => [:index]
  end

  controller :products do
    post 'product', :to => :create
    patch 'product', :to => :move
    put 'product', :to => :update
    delete 'product', :to => :destroy
  end

  controller :works do
    post 'work', :to => :create
    patch 'work', :to => :move
    put 'work', :to => :update
    delete 'work', :to => :destroy
    get 'work/output', :to => :output
  end

  controller :resources do
    post 'resource', :to => :create
    patch 'resource', :to => :move
    put 'resource', :to => :update
    delete 'resource', :to => :destroy
    get 'resource', :to => :get
  end

  controller :resource_allocations do
    get 'resource_allocations', :to => :get
    get 'resource_allocations_select', :to => :select
    post 'resource_allocations', :to => :update
  end

  controller :efforts do
    delete 'efforts/:id/delete', :to => :destroy, :as => 'effort'
    post 'efforts', :to => :create
    get 'projects/:project_id/efforts/results', :to => :results, :as => 'efforts_results'
  end

  controller :milestones do
    get 'projects/:project_id/roadmap', :to => :index, :as => 'project_roadmap'
    post 'milestone', :to => :create
    delete 'milestone/:id/delete', :to => :destroy, :as => 'milestone_delete'
  end

end

app/models/effort.rb
class Effort < ActiveRecord::Base
  scope :delphi, -> { where(:method => 0) }
  scope :expectation, -> { where(:method => [1, 2, 3]) }
  belongs_to :work
end

app/controllers/efforts_controller.rb
class EffortsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])

    if params.has_key?(:project)
      @project.estimation_method = params[:project][:estimation_method].to_f
      @project.save
    end

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => 'effort_estimation', :template => 'efforts/estimation', :disposition => 'attachment'
      end
    end
  end

  def create
    effort = params[:effort]

    if (effort[:method].to_f == 0) #delphi
      @effort = Effort.create(
        :work_id => effort[:work_id].to_f,
        :method => effort[:method].to_f,
        :name => effort[:name],
        :estimation => effort[:estimation].to_f
      )

      render :json => @effort
    else #expectation
      @work = Work.find(effort[:work_id])
      @effort = Array.new
      pessimistic = @work.expectation(1)
      realistic = @work.expectation(2)
      optimistic = @work.expectation(3)

      if pessimistic.nil?
        @effort << Effort.create(
          :work_id => effort[:work_id].to_f,
          :method => 1,
          :estimation => effort[:pessimistic].to_f
        )
      else
        pessimistic.estimation = effort[:pessimistic].to_f
        pessimistic.save
        @effort << pessimistic
      end

      if realistic.nil?
        @effort << Effort.create(
          :work_id => effort[:work_id].to_f,
          :method => 2,
          :estimation => effort[:realistic].to_f
        )
      else
        realistic.estimation = effort[:realistic].to_f
        realistic.save
        @effort << realistic
      end

      if optimistic.nil?
        @effort << Effort.create(
          :work_id => effort[:work_id].to_f,
          :method => 3,
          :estimation => effort[:optimistic].to_f
        )
      else
        optimistic.estimation = effort[:optimistic].to_f
        optimistic.save
        @effort << optimistic
      end

      render :text => @work.average_estimate(1).to_s + ' PD'
    end
  end

  def destroy
    @effort = Effort.find(params[:id])
    @effort.destroy

    render :json => @effort
  end

  def results
    @project = Project.find(params[:project_id])

    render :partial => 'delphi_results'
  end
end

app/views/efforts/_delphi.html.erb
<div id="progressbar" class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="33.33" aria-valuemin="0" aria-valuemax="100" style="width: 33.33%"></div>
</div>

<div class="panel-group" id="accordion">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#step-1"><strong>#1</strong> Hand out estimation forms</a>
      </h4>
    </div>
    <div id="step-1" class="panel-collapse collapse in">
      <div class="panel-body">
        <p class="text-muted">Pass following downloadable forms to your experts and let them have a guess of their estimated effort for each work package. It may take multiple runs to solidify the data.</p>
        <p class="text-muted">If the estimations seem not to differ much among each other, you can transfer it to <strong><em>#2</em></strong>.</p>
        <%= link_to 'Download estimation forms (.pdf)', project_efforts_path(@project, :format => :pdf), :class => 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#step-2"><strong>#2</strong> Transfer inquiry results</a>
      </h4>
    </div>
    <div id="step-2" class="panel-collapse collapse">
      <div class="panel-body">
        <% @project.work_packages.each do |work| %>
          <div class="panel panel-default">
            <div class="panel-heading"><strong><%= work.name %></strong></div>
            <div class="panel-body">
              <%= form_for :effort, :url => efforts_path, :html => { :class => 'form-inline create-estimation', :role => 'form'} do |f| %>
                <%= f.hidden_field :work_id, :value => work.id %>
                <%= f.hidden_field :method, :value => 0 %>
                <div class="form-group">New Estimation: </div>
                <div class="form-group">
                  <%= f.label :name, :class => 'sr-only' %>
                  <%= f.text_field :name, :placeholder => 'Name', :class => 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :estimation, :class => 'sr-only' %>
                  <%= f.text_field :estimation, :placeholder => 'Estimation', :class => 'form-control' %>
                </div>
                <%= f.submit 'Insert', :class => 'btn btn-default btn-sm' %>
              <% end %>
            </div>
            <table class="table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th colspan="2">Estimation</th>
                </tr>
              </thead>
              <tbody>
                <% work.efforts.delphi.each do |effort| %>
                  <tr>
                    <td><%= effort.name %></td>
                    <td><%= effort.estimation %></td>
                    <td class="text-right"><%= link_to content_tag(:span, nil, :class => 'glyphicon glyphicon-trash'), effort_path(effort), :class => 'btn btn-default btn-xs delete-estimation' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#step-3"><strong>#3</strong> View accumulated results</a>
      </h4>
    </div>
    <div id="step-3" class="panel-collapse collapse">
      <div class="panel-body"></div>
    </div>
  </div>
</div>

<script>
  $('#accordion').on('shown.bs.collapse', function(e) {
    var step = e.target.id;
    var step = parseInt(step.charAt(step.length - 1));
    
    var progress = step * 33.33;

    $('#progressbar .progress-bar').attr('aria-valuenow', progress).css('width', progress + '%')
  })

  $('#accordion').on('show.bs.collapse', function(e) {
    var step = e.target.id;
    var step = parseInt(step.charAt(step.length - 1));

    if (step == 3) {
      $.ajax({
        type : 'GET',
        url : '<%= efforts_results_path(@project) %>',
        dataType : 'html',
        success : function(data) {
          $('#step-3').find('.panel-body').html(data);
        }
      })
    }
  })

  $(document).on('click', '.delete-estimation', function(e) {
    e.preventDefault();

    var row = $(this).closest('tr');

    $.ajax({
      type : 'DELETE',
      url : $(this).attr('href'),
      dataType: 'json',
      success: function(data) {
        row.hide(400, function() { row.remove() })
      },
      error: function(xhRequest, ErrorText, thrownError) {
        console.log(xhRequest.responseText);
      }
    });
  })

  $('.create-estimation').each(function() {
    $(this).on('submit', function(e) { e.preventDefault() }).validate({
      rules: {
        'effort[name]': 'required',
        'effort[estimation]' : {
          required: true,
          number: true
        }
      },
      submitHandler: function(form) {
        var clearForm = function() {
          $(form).find('.form-control').val('');
          $(form).find('[name="effort[name]"]').focus();
        }
        var tbody = $(form).parent().next().find('tbody');
        
        $.ajax({
          type : $(form).attr('method'),
          url : $(form).attr('action'),
          dataType: 'json',
          data : $(form).serialize(),
          success: function(data) {
            var row = '<tr style="display: none"><td>' + data.name + '</td><td>' + data.estimation.toFixed(1) + '</td><td class="text-right"><a class="btn btn-default btn-xs delete-estimation" href="/efforts/' + data.id + '/delete" rel="nofollow"><span class="glyphicon glyphicon-trash"></span></a></td></tr>';
            tbody.append(row);
            tbody.children('tr:last').show(400);
            clearForm();
          },
          error: function(xhRequest, ErrorText, thrownError) {
            console.log(xhRequest.responseText);
          }
        });
      }
    })
  })
</script>

app/views/efforts/_delphi_results.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Work package</th>
      <th>Estimated Effort (Person days)</th>
    </tr>
  </thead>
  <tbody>
    <% @project.work_packages.each do |work| %>
      <tr>
        <td><%= work.name %></td>
        <td><%= work.average_estimate(0) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/efforts/_expectation.html.erb
<% @project.work_packages.each do |work| %>
  <% pessimistic = work.expectation(1) %>
  <% realistic = work.expectation(2) %>
  <% optimistic = work.expectation(3) %>
  <div class="panel panel-default work-panel">
    <div class="panel-heading"><a data-toggle="collapse" data-target="#work-<%= work.id %>" href="#"><%= work.name %></a><span class="label label-primary pull-right"><%= number_to_human(work.average_estimate(1), units: {unit: 'PD'}) %></span></div>
    <div class="panel-collapse collapse" id="work-<%= work.id %>">
      <div class="panel-body">
        <%= form_for :effort, :url => efforts_path, :method => :post, :html => { :class => 'form-inline update-estimation' } do |f| %>
          <%= f.hidden_field :work_id, :value => work.id %>
          <%= f.hidden_field :method, :value => 1 %>
          <div class="form-group col-sm-3">
            <div class="input-group">
              <span class="input-group-addon">Pessimistic</span>
              <%= f.text_field :pessimistic, :value => pessimistic.nil? ? '' : pessimistic.estimation, :class => 'form-control' %>
            </div>
          </div>
          <div class="form-group col-sm-3">
            <div class="input-group">
              <span class="input-group-addon">Realistic</span>
              <%= f.text_field :realistic, :value => realistic.nil? ? '' : realistic.estimation, :class => 'form-control' %>
            </div>
          </div>
          <div class="form-group col-sm-3">
            <div class="input-group">
              <span class="input-group-addon">Optimistic</span>
              <%= f.text_field :optimistic, :value => optimistic.nil? ? '' : optimistic.estimation, :class => 'form-control' %>
            </div>
          </div>
          <%= f.submit 'Update', :class => 'btn btn-sm btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<script>
  $('.work-panel').collapse();

  $('.update-estimation').each(function() {
    $(this).on('submit', function(e) { e.preventDefault() }).validate({
      rules: {
        'effort[pessimistic]': {
          required: true,
          number: true
        },
        'effort[realistic]': {
          required: true,
          number: true
        },
        'effort[optimistic]': {
          required: true,
          number: true
        }
      },
      submitHandler: function(form) {
        $.ajax({
          type : $(form).attr('method'),
          url : $(form).attr('action'),
          dataType: 'text',
          data : $(form).serialize(),
          success: function(data) {
            $(form).closest('.work-panel').find('.panel-heading span.label').html(data);
            $(form).closest('.panel-collapse').collapse('hide');
          },
          error: function(xhRequest, ErrorText, thrownError) {
            console.log(xhRequest.responseText);
          }
        });
      }
    })
  })

</script>

app/views/efforts/estimation.pdf.erb
<html>
<head>
<%= wicked_pdf_stylesheet_link_tag "application" %>
<style type="text/css">
  div.pagebreak { page-break-after: always;}
  div.block { display: table; margin: 2em 0;}
  div.block div.c1 {
    display: table-cell;
    vertical-align: middle;
    height: 3em;
    width: 10em;
  }
  div.block div.c2 {
    display: table-cell;
    margin-left: 30%;
    width: 40em;
    height: 3em;
    border: 2px solid #000;
  }
</style>
</head>
<body>
<% @project.work_packages.each do |work| %>
<h1>Effort Estimation</h1>
<p><strong>Work package: </strong><%= work.name %></p>
<hr/>
<div style="margin-top:2em"></div>
<div class="block">
  <div class="c1">Your name:</div>
  <div class="c2"></div>
</div>
<div class="block">
  <div class="c1">Date:</div>
  <div class="c2"></div>
</div>
<div class="block">
  <div class="c1">Estimated effort:<br/> (person days)</div>
  <div class="c2"></div>
</div>
<p><h2>Available resources</h2></p>
<hr/>
  <% work.resources.each do |resource| %>
    <p><strong style="font-size: 1.3em"><%= resource.name %></strong><br/>
    <strong>Qualification: </strong><%= resource.qualification %><br/>
    <strong>Experience: </strong><%= resource.experience %></p>
  <% end %>
<div class="pagebreak"></div>
<% end %>
</body>
</html>

app/views/efforts/index.html.erb
<%= render :partial => 'projects/navigation' %>
<h1>Effort Estimation
  <small>
    Method:
    <form style="display:inline-block">
      <%= select :project, :estimation_method, [['Delphi', 0],['Expectation', 1]], {}, :class => 'form-control' %>
    </form>
  </small>
</h1>
<!--
<nav class="navbar navbar-default" role="navigation">
  <div class="collapse navbar-collapse">
    <form class="navbar-form navbar-left">
      <div class="input-group">
        <span class="input-group-addon"><span class="glyphicon glyphicon-screenshot"></span> Estimation Method</span>
        <%= select :project, :estimation_method, [['Delphi', 0],['Expectation', 1]], {}, :class => 'form-control' %>
        <span class="input-group-btn">
          <input class="btn btn-primary" type="submit" value="Change"/>
        </span>
      </div>
    </form>
  </div>
</nav>
-->
<% if @project.estimation_method == 0 #delphi %>
  <%= render :partial => 'delphi' %>
<% else #expectation %>
  <%= render :partial => 'expectation' %>
<% end %>

<script>
  $('#project_estimation_method').change(function() {
    $(this).parent().submit();
  })
</script>