config/routes.rb
PmTool::Application.routes.draw do

  root 'welcome#index'

  resources :projects, :only => [:create, :destroy], :shallow => true do
    resources :products, :only => [:index]
    resources :works, :only => [:index]
    resources :resources, :only => [:index]
    resources :resource_allocations, :only => [:index]
    resources :efforts, :only => [:index]
  end

  controller :products do
    post 'product', :to => :create
    patch 'product', :to => :move
    put 'product', :to => :update
    delete 'product', :to => :destroy
  end

  controller :works do
    post 'work', :to => :create
    patch 'work', :to => :move
    put 'work', :to => :update
    delete 'work', :to => :destroy
    get 'work/output', :to => :output
  end

  controller :resources do
    post 'resource', :to => :create
    patch 'resource', :to => :move
    put 'resource', :to => :update
    delete 'resource', :to => :destroy
    get 'resource', :to => :get
  end

  controller :resource_allocations do
    get 'resource_allocations', :to => :get
    get 'resource_allocations_select', :to => :select
    post 'resource_allocations', :to => :update
  end

  controller :efforts do
    delete 'efforts/:id/delete', :to => :destroy, :as => 'effort'
    post 'efforts', :to => :create
    get 'projects/:project_id/efforts/results', :to => :results, :as => 'efforts_results'
  end

  controller :milestones do
    get 'projects/:project_id/roadmap', :to => :index, :as => 'project_roadmap'
    post 'milestone', :to => :create
    delete 'milestone/:id/delete', :to => :destroy, :as => 'milestone_delete'
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope { order('position') }
  scope :root, -> { where(parent_id: nil) }

  belongs_to :project
  has_ancestry :cache_depth => true
  acts_as_list :scope => 'ancestry = \'#{ancestry}\''
  before_destroy :destroy_childs

  def to_json(otions)
    super(:only => [:id, :name, :parent_id, :position, :project_id], :methods => [:depth])
  end

private
  def destroy_childs
    self.children.delete_all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:update, :move, :destroy]

  def index
    @project = Project.find(params[:project_id])
    @products = @project.products
  end

  def create
    @product = Product.create(:name => params[:product][:name], :parent_id => params[:product][:parent], :project_id => params[:project])
    render :json => @product
  end

  def move
    @product.remove_from_list
    @product.parent_id = params[:product][:parent].to_f
    @product.save
    @product.insert_at(params[:product][:position].to_f)
    @product.save

    render :json => @product
  end

  def update
    @product.name = params[:product][:name]
    @product.save

    render :json => @product
  end

  def destroy
    @product.destroy

    render :json => @product
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:product][:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :position, :project_id, :parent_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= render :partial => 'projects/navigation' %>
<h1>Product Breakdown Structure</h1>
<nav class="navbar navbar-default" role="navigation">
  <div class="collapse navbar-collapse">
    <div class="navbar-left">
      <button type="button" class="btn btn-sm navbar-btn" id="product-new"><span class="glyphicon glyphicon-plus"></span> New</button>
      <button type="button" class="btn btn-sm navbar-btn" id="product-rename"><span class="glyphicon glyphicon-pencil"></span> Rename</button>
      <button type="button" class="btn btn-sm navbar-btn" id="product-remove"><span class="glyphicon glyphicon-remove"></span> Remove</button>
    </div>
    <div class="navbar-right">
      <%= form_for :product, :url => product_path, :html => { :class => 'navbar-form navbar-left pull-right', :style => 'display: none', :role => 'form', :id => 'new-product-form' } do |f| %>
        <div class="form-group">
          <%= f.text_field :name, :class => 'form-control', :placeholder => 'Enter node name' %>
        </div>
        <%= f.submit 'Insert', :class => 'btn btn-primary btn-sm' %>
      <% end %>
    </div>
  </div>
</nav>

<div id="jstree"></div>
<script>
  var tree = $('#jstree');
  $('#jstree')
    .jstree({
      "core" : {
        "check_callback" : true,
        "data" : {
          "url" : "<%= project_products_path(@project, :format => :json) %>",
          "data" : function(node) {
            return { 'id' : node.id, 'text' : 'test' };
          }
        },
      },
      "types" : {
        '#'  : { "icon" : "glyphicon glyphicon-folder-open", "valid_children" : [] },
        'd0' : { "icon" : "glyphicon glyphicon-folder-open", "valid_children" : ['d1'] },
        'd1' : { "icon" : "glyphicon glyphicon-folder-open", "valid_children" : ['d2'] },
        'd2' : { "icon" : "glyphicon glyphicon-folder-open", "valid_children" : ['d3'] },
        'd3' : { "icon" : "glyphicon glyphicon-tasks", "max_children" : 0, "valid_children" : [] }
      },
      "plugins" : [ "dnd", "types", "wholerow" ]
  }).bind('ready.jstree', function() {
    $(this).jstree('open_all').jstree('open_all').jstree('open_all');
  }).bind('set_text.jstree', function(event, data) {
    if (!!data.text) {
      var product = {
        'id' : data.obj.id,
        'name' : data.obj.text
      };
      AjaxProduct('PUT', product, null);
    }
  }).bind('delete_node.jstree', function(event, data) {
    var product = {
      'id' : data.node.id
    }
    AjaxProduct('DELETE', product, null);
  }).bind('move_node.jstree', function(event, data) {
    var product = {
      'id' : data.node.id,
      'parent' : data.parent,
      'position' : data.position + 1
    }
    AjaxProduct('PATCH', product, null);
  });

  function AjaxProduct(action, product, callback) {
    $.ajax({
      type : action,
      url : '<%= product_path %>',
      dataType: 'json',
      data : { 'project' : <%= @project.id %>, 'product' : product },
      success: callback,
      error: function(xhRequest, ErrorText, thrownError) {
        console.log(xhRequest.responseText);
      }
    });
  }

  $('#product-new').click(function() {
    $('#product_name').val('');
    $('#new-product-form').toggle('slide', function () { $('#product_name').focus() });
  });

  $('#product-rename').click(function() {
    var ref = $('#jstree').jstree(true),
        sel = ref.get_selected();

    if(!sel.length) { return false; }
    sel = sel[0];
    ref.edit(sel);
  });

  $('#product-remove').click(function() {
    var ref = $('#jstree').jstree(true),
        sel = ref.get_selected();

    if (!sel.length) { return false; }
    ref.delete_node(sel);
  });

  $('#new-product-form').validate({
    rules: {
      'product[name]': {
        required : true,
        validParentNodeSelected : true
      }
    },
    messages: {
      'product[name]': {
        validParentNodeSelected : 'Please select a valid parent node.'
      }
    },
    submitHandler: function(form) {
      var val = $('#product_name').val();
      var ref = $('#jstree').jstree(true),
          sel = ref.get_selected();

      sel = ref.get_node(sel[0]);

      if (sel.type != 'd3' || sel.type == '#') {
        var product = { 'name' : val, 'parent' : sel.id }

        AjaxProduct('POST', product, function(data) {
          ref.create_node(sel,
            {
              'id' : data.id,
              'text' : data.name,
              'type' : 'd' + data.depth
            }
          );
          ref.open_node(sel);
        })

        $('#new-product-form').hide('slide');
      }
    }
  })
</script>